### ISSUE TITLE
game black screen on start 

### ISSUE THREAD

**Issue by net528890** [hcdotnet/holocure#1]
![image](https://user-images.githubusercontent.com/99803184/223133668-74887d16-03f3-4749-a66c-2cbac41d26fb.png)

![image](https://user-images.githubusercontent.com/99803184/223133846-8d9b8bc7-cfb0-4d32-8128-7cb734a8793b.png)

[window  , 64 bit ]
build no error
![image](https://user-images.githubusercontent.com/99803184/223180824-a3bf37de-c6ea-46dc-ae9e-370a118f9683.png)

**Comment by steviegt6** [comment]
Because that's all there is so far 😭
